language: node_js
node_js: 10
stages:
  - test
  - publish
jobs:
  include:
    - stage: test
      script:
        - set -e
        - yarn
        - yarn build
        - yarn test
    - stage: publish
      script:
        - set -e
        - yarn
        - yarn build
        - yarn publish

