language: node_js
node_js: 10
stages:
  - test
  - release
jobs:
  include:
    - stage: test
      script:
        - set -e
        - yarn
        - yarn build
        - yarn test
    - stage: release
      script:
        - set -e
        - yarn
        - yarn build
        - yarn release

